version: '3'

services:

  snipe-mysql:
    container_name: snipe-mysql
    image: mysql:5.6
    env_file:
      - ./.env
    volumes:
      - snipesql-vol:/var/lib/mysql
    expose:
      - "3306"

  snipe-it:
    image: amrhegazy/sinpe
    env_file:
      - ./.env
    ports:
      - "8080:80"
    depends_on:
      - snipe-mysql

volumes:
  snipesql-vol:
